CC=gcc
CFLAGS=-Wall 


all : htoi
.PHONY : all

htoi: main.o get_line.o htoi.o
	$(CC) $(CFLAGS) -o htoi main.o get_line.o htoi.o 

main.o : main.c 
	$(CC) -Wall -c -o main.o main.c

get_line.o : get_line.c 
	$(CC) -Wall -c -o get_line.o get_line.c

htoi.o : htoi.c 
	$(CC) -Wall -c -o htoi.o htoi.c
	
debug:clean main.c get_line.c htoi.c
	$(CC) -Wall -g -o occ main.c get_line.c htoi.c 
	gdb -tui  occ

	
	
.PHONY: clean
clean : 
	rm -rf *.o 