CC=gcc
CFLAGS=-Wall 


all : any
.PHONY : all

any: main.o any.o
	$(CC) $(CFLAGS) -o any main.o any.o 

main.o : main.c 
	$(CC) -Wall -c -o main.o main.c

setbits.o : setbits.c 
	$(CC) -Wall -c -o setbits.o setbits.c
	
debug:clean main.c setbits.c
	$(CC) -Wall -g -o occ main.c setbits.c 
	gdb -tui  occ

	
	
.PHONY: clean
clean : 
	rm -rf *.o 